spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 1234
    username: postgres
    url: jdbc:postgresql://localhost/postgres
  application:
    name: weather-report

datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234

jpa:
    hibernate:
    ddl-auto: update
    show-sql: true

server:
  error:
    include-message: always

#logging:
#    level:
#    org.springframework.security: trace
